l_english:
  settings_desc_1:0"Number of Tank Divisions"
  settings_desc_2:0"Number of Infantry Divisions"
  settings_desc_3:0"Armor Division Attack"
  settings_desc_4:0"Infantry Division Attack"
  settings_desc_5:0"Armor Division Speed"
  settings_desc_6:0"Division Speed"
  settings_desc_7:0"Armor Division Defense"
  settings_desc_8:0"Infantry Division Defense"
  settings_desc_9:0"Supply Usage"
  settings_desc_10:0"Max Planning"
  settings_desc_11:0"Terrain Penalty Reduction"  
  settings_desc_12:0"Army Organization Factor"
  settings_desc_13:0"Max Entrenchment"
  value_desc_1:0"[?onevsonevar|G+%0]"
  value_desc_2:0"[?onevsonevar|G0]"
  value_desc_3:0"[?onevsonevar|G-%0]"
  start_desc_1:0"Start"
  start_desc_2:0"Restart"
  day_loc:0 "Days : [?passed_days]"
  win_day_loc_SOV:0 "SOV Win : [?win_days] Days"
  win_day_loc_GER:0 "GER Win : [?win_days] Days"
  Barb_Modifiers:0 "1 VS 1 Modifier"